#!/usr/bin/env python3
"""
Documentation parser for Cute Framework headers
Parses header files and generates markdown documentation
"""

import os
import sys
import re
from pathlib import Path
from typing import List, Dict, Optional, Tuple
from dataclasses import dataclass, field
from enum import Enum


class DocType(Enum):
    """Documentation types"""
    EMPTY = 0
    ENUM = 1
    FUNCTION = 2
    STRUCT = 3


# Configuration for category-related links
CATEGORY_RELATED_LINKS = {
    'allocator': ['- [Allocator](../topics/allocator)'],
    'app': [
        '- [Application Window](../topics/application_window.md)',
        '- [Game Loop and Time](../topics/game_loop_and_time.md)'
    ],
    'array': ['- [Data Structures](../topics/data_structures.md)'],
    'atomics': ['- [Atomics](../topics/atomics.md)'],
    'base64': ['- [Serialization](../topics/serialization.md)'],
    'collision': ['- [Collision](../topics/collision.md)'],
    'coroutine': ['- [Coroutines](../topics/coroutines.md)'],
    'draw': ['- [Drawing](../topics/drawing.md)'],
    'ecs': ['- [Entity Component System](../topics/entity_component_system.md)'],
    'file': ['- [Virtual File System](../topics/virtual_file_system.md)'],
    'graphics': ['- [Low Level Graphics](../topics/low_level_graphics.md)'],
    'haptic': ['- [Input](../topics/input.md)'],
    'hash': ['- [Data Structures](../topics/data_structures.md)'],
    'input': ['- [Input](../topics/input.md)'],
    'list': ['- [Data Structures](../topics/data_structures.md)'],
    'math': ['- [Collision](../topics/collision.md)'],
    'multithreading': [
        '- [Atomics](../topics/atomics.md)',
        '- [Multithreading](../topics/multithreading.md)'
    ],
    'net': ['- [Networking](../topics/networking.md)'],
    'path': ['- [Virtual File System](../topics/virtual_file_system.md)'],
    'pathfinding': ['- [Path Finding](../topics/pathfinding.md)'],
    'random': ['- [Random Numbers](../topics/random_numbers.md)'],
    'serialization': ['- [Serialization](../topics/serialization.md)'],
    'sprite': ['- [Drawing](../topics/drawing.md)'],
    'string': ['- [Strings](../topics/strings.md)'],
    'time': ['- [Game Loop and Time](../topics/game_loop_and_time.md)'],
    'text': [
        '- [Drawing](../topics/drawing.md)',
        '- [Input](../topics/input.md)'
    ],
    'web': ['- [Networking](../topics/networking.md)']
}


@dataclass
class Doc:
    """Single documentation entry"""
    type: DocType = DocType.EMPTY
    path: Optional[Path] = None
    web_category: str = ''
    title: str = ''
    file: str = ''
    brief: str = ''
    this_index: int = -1
    signature: str = ''
    param_names: List[str] = field(default_factory=list)
    param_briefs: List[str] = field(default_factory=list)
    enum_entries: List[str] = field(default_factory=list)
    enum_entry_briefs: List[str] = field(default_factory=list)
    member_briefs: List[str] = field(default_factory=list)
    member_functions: List[int] = field(default_factory=list)
    members: List[str] = field(default_factory=list)
    return_value: str = ''
    example_brief: str = ''
    example: str = ''
    remarks: str = ''
    related: List[str] = field(default_factory=list)

    def emit_title(self, fp):
        """Emit the title section"""
        fp.write("[//]: # (This file is automatically generated by Cute Framework's docs parser.)\n")
        fp.write("[//]: # (Do not edit this file by hand!)\n")
        fp.write("[//]: # (See: https://github.com/RandyGaul/cute_framework/blob/master/scripts/docs_parser.py)\n")
        fp.write(f"# {self.title}\n\n")
        link = self.web_category.lower()
        fp.write(f"Category: [{self.web_category}](../api_reference.md#{link})  \n")
        fp.write(f"GitHub: [{self.file}](https://github.com/RandyGaul/cute_framework/blob/master/include/{self.file})  \n---\n\n")

    def emit_brief(self, fp):
        """Emit the brief description"""
        if self.brief:
            fp.write(f"{self.brief}\n\n")

    def emit_signature(self, fp):
        """Emit the function signature"""
        if self.signature:
            fp.write(f"```cpp\n{self.signature}\n```\n\n")

    def emit_members(self, fp):
        """Emit struct members"""
        if not self.members:
            return

        fp.write("Struct Members | Description\n")
        fp.write("--- | ---\n")
        for member, brief in zip(self.members, self.member_briefs):
            fp.write(f"`{member}` | {brief}\n")
        fp.write("\n")

    def emit_member_function_links(self, fp, docs_list):
        """Emit links to member functions"""
        if not self.member_functions:
            return

        fp.write("Functions | Description\n")
        fp.write("--- | ---\n")
        for index in self.member_functions:
            doc = docs_list[index]
            # TODO: Linkify title
            fp.write(f"{doc.title} | {doc.brief}\n")
        fp.write("\n")

    def emit_params(self, fp):
        """Emit parameter descriptions"""
        if not self.param_names:
            return

        fp.write("Parameters | Description\n")
        fp.write("--- | ---\n")
        for name, brief in zip(self.param_names, self.param_briefs):
            fp.write(f"{name} | {brief}\n")
        fp.write("\n")

    def emit_enum_entries(self, fp):
        """Emit enum value descriptions"""
        fp.write("## Values\n\n")
        fp.write("Enum | Description\n")
        fp.write("--- | ---\n")
        for entry, brief in zip(self.enum_entries, self.enum_entry_briefs):
            fp.write(f"{entry} | {brief}\n")
        fp.write("\n")

    def emit_return(self, fp):
        """Emit return value description"""
        if self.return_value:
            fp.write(f"## Return Value\n\n{self.return_value}\n\n")

    def emit_example(self, fp):
        """Emit code example"""
        if not self.example:
            return

        fp.write("## Code Example\n\n")
        if self.example_brief:
            fp.write(f"{self.example_brief}\n\n")
        fp.write(f"```cpp{self.example}```\n\n")

    def emit_remarks(self, fp):
        """Emit remarks section"""
        if self.remarks:
            fp.write("## Remarks\n\n")
            fp.write(f"{self.remarks}\n\n")

    def emit_related(self, fp):
        """Emit related pages"""
        if not self.related:
            return

        fp.write("## Related Pages\n\n")
        for rel in self.related:
            fp.write(f"{rel}\n")


class Scanner:
    """Scanner for parsing documentation"""

    def __init__(self, content: str, filename: str):
        self.content = content
        self.filename = filename
        self.pos = 0

    def done(self) -> bool:
        """Check if scanner is at end of content"""
        return self.pos >= len(self.content)

    def peek(self, length: int = 1) -> str:
        """Peek ahead without advancing"""
        if self.pos + length > len(self.content):
            return ''
        return self.content[self.pos:self.pos + length]

    def advance(self, count: int = 1):
        """Advance scanner position"""
        self.pos = min(self.pos + count, len(self.content))

    def skip_whitespace(self):
        """Skip whitespace characters"""
        while not self.done() and self.content[self.pos].isspace():
            self.advance()

    def parse_token(self) -> Optional[str]:
        """Parse next token"""
        self.skip_whitespace()

        if self.done():
            return None

        token = ''
        while not self.done() and not self.content[self.pos].isspace():
            token += self.content[self.pos]
            self.advance()

        return token if token else None

    def parse_paragraph(self, example: bool = False) -> str:
        """Parse a paragraph of documentation"""
        paragraph = ''

        while not self.done():
            ch = self.content[self.pos]

            if ch == '\n':
                paragraph += ch
                self.advance()

                # Check for end of comment
                if self.peek(3) == ' */' or self.peek(2) == '*/':
                    break
                elif self.peek(3) == ' * ':
                    self.advance(3)
                elif self.peek(2) == ' *':
                    self.advance(2)
            elif ch == '@' and not example:
                break
            elif self.peek(2) == '*/':
                break
            else:
                if ch != '\r':
                    paragraph += ch
                self.advance()

        if not example:
            # Clean up the paragraph
            paragraph = paragraph.strip()
            # Normalize indentation
            paragraph = re.sub(r'\n\s+', '\n', paragraph)
        else:
            # For examples, preserve formatting but adjust indentation
            paragraph = paragraph.replace('\n    ', '\n')

        return paragraph

    def parse_single_comment_line(self) -> str:
        """Parse a single line of comment"""
        line = ''

        # Skip initial whitespace and asterisk
        if self.peek(3) == ' * ':
            self.advance(3)
        elif self.peek(2) == ' *':
            self.advance(2)

        # Read until newline
        while not self.done() and self.content[self.pos] != '\n':
            line += self.content[self.pos]
            self.advance()

        return line.strip()

    def parse_line(self) -> str:
        """Parse a line of code"""
        line = ''

        # Skip newline if present
        if not self.done() and self.content[self.pos] == '\n':
            self.advance()

        # Read until newline
        while not self.done() and self.content[self.pos] != '\n':
            line += self.content[self.pos]
            self.advance()

        return line.strip()


class DocsParser:
    """Main documentation parser class"""

    def __init__(self, include_dir: Path, docs_dir: Path):
        self.include_dir = Path(include_dir)
        self.docs_dir = Path(docs_dir)
        self.docs: List[Doc] = []
        self.categories: Dict[str, bool] = {}
        self.category_index_lists: Dict[str, List[str]] = {}
        self.page_to_doc_index: Dict[str, int] = {}
        self.current_doc = Doc()
        self.current_file = ''

    def parse_all(self):
        """Parse all header files and generate documentation"""
        # Find all header files
        header_files = sorted(self.include_dir.glob('*.h'))

        print(f"Found {len(header_files)} header files to parse")

        # Parse each header
        for file in header_files:
            self.parse_header(file)

        # Auto-generate links
        self.auto_generate_all_links()

        # Save documentation files
        self.save_all_docs()

        # Generate API reference
        self.generate_api_reference()

        # Clean up old files
        self.cleanup_old_docs()

        print("docsparser: Success!")

    def parse_header(self, filepath: Path):
        """Parse a single header file"""
        self.current_file = filepath.name
        content = filepath.read_text()

        scanner = Scanner(content, self.current_file)

        while not scanner.done():
            token = scanner.parse_token()

            if token and token.startswith('@'):
                if token == '@enum':
                    self.parse_enum(scanner)
                elif token == '@function':
                    self.parse_function(scanner)
                elif token == '@struct':
                    self.parse_struct(scanner)

    def parse_enum(self, scanner: Scanner):
        """Parse enum documentation"""
        self.current_doc = Doc()
        self.current_doc.type = DocType.ENUM
        self.current_doc.title = scanner.parse_paragraph().strip()
        self.current_doc.file = self.current_file

        # Parse enum documentation
        while not scanner.done():
            token = scanner.parse_token()
            if token == '*/':
                break

            if token and token.startswith('@'):
                self.parse_command(scanner, token)

        # Parse enum entries
        while not scanner.done():
            token = scanner.parse_token()

            if token and token.startswith('@'):
                if token == '@entry':
                    self.current_doc.enum_entry_briefs.append(
                        scanner.parse_paragraph().strip()
                    )
                elif token == '@end':
                    break
            elif token and 'CF_ENUM(' in token:
                # Extract enum entry name
                match = re.search(r'CF_ENUM\(([^,]+)', token)
                if match:
                    self.current_doc.enum_entries.append(match.group(1))

        self.flush_doc()

    def parse_function(self, scanner: Scanner):
        """Parse function documentation"""
        self.current_doc = Doc()
        self.current_doc.type = DocType.FUNCTION
        self.current_doc.file = self.current_file

        self.parse_comment_block(scanner)

        # Parse function signature
        signature = scanner.parse_line().strip()
        signature = (signature.replace('CF_API ', '')
                             .replace('CF_CALL ', '')
                             .replace('CF_INLINE ', ''))

        # Remove trailing brace if present
        if ' {' in signature:
            signature = signature[:signature.index(' {')]

        self.current_doc.signature = signature
        self.flush_doc()

    def parse_struct(self, scanner: Scanner):
        """Parse struct documentation"""
        self.current_doc = Doc()
        self.current_doc.type = DocType.STRUCT
        self.current_doc.file = self.current_file

        self.parse_comment_block(scanner)
        doc_index = len(self.docs)
        self.flush_doc()

        # Parse struct members and functions
        while not scanner.done():
            token = scanner.parse_token()

            if token and token.startswith('@'):
                if token == '@member':
                    brief = scanner.parse_paragraph().strip()
                    scanner.parse_token()  # Skip */
                    member = (scanner.parse_line().strip()
                             .replace('CF_INLINE ', '')
                             .replace(';', ''))
                    self.docs[doc_index].member_briefs.append(brief)
                    self.docs[doc_index].members.append(member)
                elif token == '@function':
                    self.docs[doc_index].member_functions.append(len(self.docs))
                    self.parse_function(scanner)
                    self.docs[-1].this_index = doc_index
                elif token == '@end':
                    break

    def parse_comment_block(self, scanner: Scanner):
        """Parse a comment block"""
        self.current_doc.title = scanner.parse_paragraph().strip()

        while not scanner.done():
            token = scanner.parse_token()
            if token == '*/':
                break

            if token and token.startswith('@'):
                self.parse_command(scanner, token)

    def parse_command(self, scanner: Scanner, command: str):
        """Parse a documentation command"""
        if command == '@brief':
            self.current_doc.brief = scanner.parse_paragraph().strip()
        elif command == '@example':
            self.current_doc.example_brief = scanner.parse_single_comment_line().strip()
            self.current_doc.example = scanner.parse_paragraph(True)
        elif command == '@remarks':
            self.current_doc.remarks = scanner.parse_paragraph().strip()
        elif command == '@related':
            self.current_doc.related = scanner.parse_paragraph().strip().split()
        elif command == '@param':
            param_name = scanner.parse_token()
            if param_name:
                self.current_doc.param_names.append(param_name)
                self.current_doc.param_briefs.append(scanner.parse_paragraph().strip())
        elif command == '@return':
            self.current_doc.return_value = scanner.parse_paragraph().strip()
        elif command == '@category':
            self.current_doc.web_category = scanner.parse_paragraph().strip()
            self.categories[self.current_doc.web_category] = True

    def flush_doc(self):
        """Save current doc and reset"""
        if not self.current_doc.title:
            return

        # Generate file path
        path = self.docs_dir / self.current_doc.web_category
        filename = self.current_doc.title.lower().replace(' ', '_') + '.md'
        self.current_doc.path = path / filename

        # Check for duplicates
        if filename in self.page_to_doc_index:
            other_doc = self.docs[self.page_to_doc_index[filename]]
            raise ValueError(f"Duplicate page for {filename} (found in {self.current_doc.file}, "
                           f"previously in {other_doc.file})")

        self.page_to_doc_index[filename] = len(self.docs)

        if self.current_doc.web_category not in self.category_index_lists:
            self.category_index_lists[self.current_doc.web_category] = []
        self.category_index_lists[self.current_doc.web_category].append(self.current_doc.title)

        self.docs.append(self.current_doc)
        self.current_doc = Doc()

    def auto_generate_all_links(self):
        """Auto-generate links for all documentation"""
        for doc in self.docs:
            doc.brief = self.auto_generate_links(doc.brief)
            doc.param_briefs = [self.auto_generate_links(b) for b in doc.param_briefs]
            doc.enum_entry_briefs = [self.auto_generate_links(b) for b in doc.enum_entry_briefs]
            doc.member_briefs = [self.auto_generate_links(b) for b in doc.member_briefs]
            doc.return_value = self.auto_generate_links(doc.return_value)
            doc.example_brief = self.auto_generate_links(doc.example_brief)
            doc.example = self.auto_generate_links(doc.example)
            doc.remarks = self.auto_generate_links(doc.remarks)

            # Process related links
            new_related = []
            for related in doc.related:
                if related != doc.title:
                    new_related.append(self.linkify(related, related, False) + "  ")
            doc.related = new_related

    def auto_generate_links(self, text: str) -> str:
        """Auto-generate links in text"""
        if not text:
            return text

        result = text

        # Find all text in backticks
        matches = re.findall(r'`([^`]+)`', text)
        for match in matches:
            if self.doc_has_link(match):
                link = self.doc_get_link(match)
                replacement = f"[{match}](..{link})"
                result = result.replace(f"`{match}`", replacement)

        return result

    def linkify(self, text: str, scan: str, use_ticks: bool = True) -> str:
        """Create a link if possible"""
        if self.doc_has_link(scan):
            link = self.doc_get_link(scan)
            coded_link = f"[{scan}](..{link})"
            scan_formatted = f"`{scan}`" if use_ticks else scan
            return text.replace(scan_formatted, coded_link)
        return text

    def doc_has_link(self, title: str) -> bool:
        """Check if a doc link exists for title"""
        filename = title.lower().replace(' ', '_') + '.md'
        return filename in self.page_to_doc_index

    def doc_get_link(self, title: str) -> str:
        """Get the link for a doc title"""
        filename = title.lower().replace(' ', '_') + '.md'
        if filename not in self.page_to_doc_index:
            return ''

        index = self.page_to_doc_index[filename]
        doc = self.docs[index]

        # Create relative path
        relative_path = doc.path.relative_to(self.docs_dir)
        return '/' + str(relative_path).replace('\\', '/')

    def save_all_docs(self):
        """Save all documentation files"""
        for doc in self.docs:
            # Create directory if needed
            doc.path.parent.mkdir(parents=True, exist_ok=True)

            # Write doc file
            with open(doc.path, 'w') as fp:
                if doc.type == DocType.ENUM:
                    doc.emit_title(fp)
                    doc.emit_brief(fp)
                    doc.emit_enum_entries(fp)
                    doc.emit_example(fp)
                    doc.emit_remarks(fp)
                    doc.emit_related(fp)
                elif doc.type == DocType.FUNCTION:
                    doc.emit_title(fp)
                    doc.emit_brief(fp)
                    doc.emit_signature(fp)
                    doc.emit_params(fp)
                    doc.emit_return(fp)
                    doc.emit_example(fp)
                    doc.emit_remarks(fp)
                    doc.emit_related(fp)
                elif doc.type == DocType.STRUCT:
                    doc.emit_title(fp)
                    doc.emit_brief(fp)
                    doc.emit_members(fp)
                    doc.emit_member_function_links(fp, self.docs)
                    doc.emit_example(fp)
                    doc.emit_remarks(fp)
                    doc.emit_related(fp)

            print(f"Wrote {doc.path}")

    def generate_api_reference(self):
        """Generate the main API reference file"""
        path = self.docs_dir / 'api_reference.md'

        with open(path, 'w') as fp:
            fp.write("[//]: # (This file is automatically generated by Cute Framework's docs parser.)\n")
            fp.write("[//]: # (Do not edit this file by hand!)\n")
            fp.write("[//]: # (See: https://github.com/RandyGaul/cute_framework/blob/master/scripts/docs_parser.py)\n")
            fp.write("# API Reference\n\n")
            fp.write("This is a list of all functions in Cute Framework organized by categories. ")
            fp.write("This is great for users that want to see all the available functionality laid out plainly.\n\n\n")

            # Sort categories alphabetically
            sorted_categories = sorted(self.categories.keys(), key=str.lower)

            for category in sorted_categories:
                fp.write(f"## {category}\n\n")

                # Get all items for this category
                items = self.category_index_lists.get(category, [])

                # Separate by type
                functions = []
                structs = []
                enums = []

                for title in items:
                    filename = title.lower().replace(' ', '_') + '.md'
                    if filename in self.page_to_doc_index:
                        index = self.page_to_doc_index[filename]
                        doc = self.docs[index]

                        if doc.type == DocType.FUNCTION:
                            functions.append(title)
                        elif doc.type == DocType.STRUCT:
                            structs.append(title)
                        elif doc.type == DocType.ENUM:
                            enums.append(title)

                # Output functions
                if functions:
                    self.save_api_reference_links(fp, category,
                                                 sorted(functions, key=str.lower),
                                                 'functions')

                # Output structs
                if structs:
                    self.save_api_reference_links(fp, category,
                                                 sorted(structs, key=str.lower),
                                                 'structs')

                # Output enums
                if enums:
                    self.save_api_reference_links(fp, category,
                                                 sorted(enums, key=str.lower),
                                                 'enums')

        print(f"Wrote {path}")

    def save_api_reference_links(self, fp, category: str, pages: List[str], type_name: str):
        """Save links for API reference"""
        if not pages:
            return

        fp.write(f"### {type_name}\n")
        for page in pages:
            page_lower = page.lower().replace(' ', '_')
            fp.write(f"- [{page}]({category}/{page_lower}.md)\n")
        fp.write("\n\n")

        # Add related links if any
        related = CATEGORY_RELATED_LINKS.get(category)
        if related:
            fp.write("### Related Reading\n")
            for link in related:
                fp.write(f"{link}\n")
            fp.write("\n")

    def cleanup_old_docs(self):
        """Clean up old documentation files"""
        for category in self.categories.keys():
            dir_path = self.docs_dir / category
            if not dir_path.exists():
                continue

            for file in dir_path.glob('*.md'):
                filename = file.name
                if filename in ['enums.md', 'functions.md', 'structs.md']:
                    continue

                if filename not in self.page_to_doc_index:
                    file.unlink()
                    print(f"Removed old file: {file}")


def main():
    """Main execution"""
    # Determine paths relative to script location
    script_dir = Path(__file__).parent
    project_root = script_dir.parent

    include_dir = project_root / 'include'
    docs_dir = project_root / 'docs'

    if not include_dir.exists():
        print(f"Error: Include directory not found at {include_dir}")
        sys.exit(1)

    if not docs_dir.exists():
        print(f"Error: Docs directory not found at {docs_dir}")
        sys.exit(1)

    print(f"Parsing headers from: {include_dir}")
    print(f"Writing docs to: {docs_dir}")

    parser = DocsParser(include_dir, docs_dir)
    parser.parse_all()


if __name__ == '__main__':
    main()