#!/usr/bin/env ruby

require 'fileutils'
require 'pathname'

# Documentation parser for Cute Framework headers
# Parses header files and generates markdown documentation
class DocsParser
  # Documentation types
  DOC_TYPE = {
    empty: 0,
    enum: 1,
    function: 2,
    struct: 3
  }.freeze

  # Configuration for category-related links
  CATEGORY_RELATED_LINKS = {
    'allocator' => ['- [Allocator](../topics/allocator)'],
    'app' => [
      '- [Application Window](../topics/application_window.md)',
      '- [Game Loop and Time](../topics/game_loop_and_time.md)'
    ],
    'array' => ['- [Data Structures](../topics/data_structures.md)'],
    'atomics' => ['- [Atomics](../topics/atomics.md)'],
    'base64' => ['- [Serialization](../topics/serialization.md)'],
    'collision' => ['- [Collision](../topics/collision.md)'],
    'coroutine' => ['- [Coroutines](../topics/coroutines.md)'],
    'draw' => ['- [Drawing](../topics/drawing.md)'],
    'ecs' => ['- [Entity Component System](../topics/entity_component_system.md)'],
    'file' => ['- [Virtual File System](../topics/virtual_file_system.md)'],
    'graphics' => ['- [Low Level Graphics](../topics/low_level_graphics.md)'],
    'haptic' => ['- [Input](../topics/input.md)'],
    'hash' => ['- [Data Structures](../topics/data_structures.md)'],
    'input' => ['- [Input](../topics/input.md)'],
    'list' => ['- [Data Structures](../topics/data_structures.md)'],
    'math' => ['- [Collision](../topics/collision.md)'],
    'multithreading' => [
      '- [Atomics](../topics/atomics.md)',
      '- [Multithreading](../topics/multithreading.md)'
    ],
    'net' => ['- [Networking](../topics/networking.md)'],
    'path' => ['- [Virtual File System](../topics/virtual_file_system.md)'],
    'pathfinding' => ['- [Path Finding](../topics/pathfinding.md)'],
    'random' => ['- [Random Numbers](../topics/random_numbers.md)'],
    'serialization' => ['- [Serialization](../topics/serialization.md)'],
    'sprite' => ['- [Drawing](../topics/drawing.md)'],
    'string' => ['- [Strings](../topics/strings.md)'],
    'time' => ['- [Game Loop and Time](../topics/game_loop_and_time.md)'],
    'text' => [
      '- [Drawing](../topics/drawing.md)',
      '- [Input](../topics/input.md)'
    ],
    'web' => ['- [Networking](../topics/networking.md)']
  }.freeze

  # Single documentation entry
  class Doc
    attr_accessor :type, :path, :web_category, :title, :file, :brief, :this_index,
                  :signature, :param_names, :param_briefs, :enum_entries,
                  :enum_entry_briefs, :member_briefs, :member_functions,
                  :members, :return_value, :example_brief, :example,
                  :remarks, :related

    def initialize
      @type = :empty
      @path = nil
      @web_category = ''
      @title = ''
      @file = ''
      @brief = ''
      @this_index = -1
      @signature = ''
      @param_names = []
      @param_briefs = []
      @enum_entries = []
      @enum_entry_briefs = []
      @member_briefs = []
      @member_functions = []
      @members = []
      @return_value = ''
      @example_brief = ''
      @example = ''
      @remarks = ''
      @related = []
    end

    def emit_title(fp)
      fp.puts "[//]: # (This file is automatically generated by Cute Framework's docs parser.)"
      fp.puts "[//]: # (Do not edit this file by hand!)"
      fp.puts "[//]: # (See: https://github.com/RandyGaul/cute_framework/blob/master/scripts/docs_parser.rb)"
      fp.puts "# #{@title}\n\n"
      link = @web_category.downcase
      fp.puts "Category: [#{@web_category}](../api_reference.md##{link})  "
      fp.puts "GitHub: [#{@file}](https://github.com/RandyGaul/cute_framework/blob/master/include/#{@file})  \n---\n\n"
    end

    def emit_brief(fp)
      fp.puts "#{@brief}\n\n" unless @brief.empty?
    end

    def emit_signature(fp)
      fp.puts "```cpp\n#{@signature}\n```\n\n" unless @signature.empty?
    end

    def emit_members(fp)
      return if @members.empty?

      fp.puts "Struct Members | Description"
      fp.puts "--- | ---"
      @members.each_with_index do |member, i|
        fp.puts "`#{member}` | #{@member_briefs[i]}"
      end
      fp.puts
    end

    def emit_member_function_links(fp, docs_list)
      return if @member_functions.empty?

      fp.puts "Functions | Description"
      fp.puts "--- | ---"
      @member_functions.each do |index|
        doc = docs_list[index]
        # TODO: Linkify title
        fp.puts "#{doc.title} | #{doc.brief}"
      end
      fp.puts
    end

    def emit_params(fp)
      return if @param_names.empty?

      fp.puts "Parameters | Description"
      fp.puts "--- | ---"
      @param_names.each_with_index do |name, i|
        fp.puts "#{name} | #{@param_briefs[i]}"
      end
      fp.puts
    end

    def emit_enum_entries(fp)
      fp.puts "## Values\n\n"
      fp.puts "Enum | Description"
      fp.puts "--- | ---"
      @enum_entries.each_with_index do |entry, i|
        fp.puts "#{entry} | #{@enum_entry_briefs[i]}"
      end
      fp.puts
    end

    def emit_return(fp)
      unless @return_value.empty?
        fp.puts "## Return Value\n\n#{@return_value}\n\n"
      end
    end

    def emit_example(fp)
      return if @example.empty?

      fp.puts "## Code Example\n\n"
      fp.puts "#{@example_brief}\n\n" unless @example_brief.empty?
      fp.puts "```cpp#{@example}```\n\n"
    end

    def emit_remarks(fp)
      unless @remarks.empty?
        fp.puts "## Remarks\n\n"
        fp.puts "#{@remarks}\n\n"
      end
    end

    def emit_related(fp)
      return if @related.empty?

      fp.puts "## Related Pages\n\n"
      @related.each do |rel|
        fp.puts rel
      end
    end
  end

  def initialize(include_dir, docs_dir)
    @include_dir = Pathname.new(include_dir)
    @docs_dir = Pathname.new(docs_dir)
    @docs = []
    @categories = {}
    @category_index_lists = Hash.new { |h, k| h[k] = [] }
    @page_to_doc_index = {}
    @current_doc = Doc.new
    @current_file = ''
  end

  def parse_all
    # Find all header files
    header_files = Dir.glob(@include_dir.join('*.h')).sort

    puts "Found #{header_files.length} header files to parse"

    # Parse each header
    header_files.each do |file|
      if File.basename(file).end_with?('.h')
        parse_header(file)
      end
    end

    # Auto-generate links
    auto_generate_all_links

    # Save documentation files
    save_all_docs

    # Generate API reference
    generate_api_reference

    # Clean up old files
    cleanup_old_docs

    puts "docsparser: Success!"
  end

  private

  def parse_header(filepath)
    @current_file = File.basename(filepath)
    content = File.read(filepath)

    # Process documentation comments
    scanner = Scanner.new(content, @current_file)

    while !scanner.done?
      token = scanner.parse_token

      if token&.start_with?('@')
        case token
        when '@enum'
          parse_enum(scanner)
        when '@function'
          parse_function(scanner)
        when '@struct'
          parse_struct(scanner)
        else
          # Skip unknown commands at top level
        end
      end
    end
  end

  def parse_enum(scanner)
    @current_doc = Doc.new
    @current_doc.type = :enum
    @current_doc.title = scanner.parse_paragraph.strip
    @current_doc.file = @current_file

    # Parse enum documentation
    while !scanner.done?
      token = scanner.parse_token
      break if token == '*/'

      if token&.start_with?('@')
        parse_command(scanner, token)
      end
    end

    # Parse enum entries
    while !scanner.done?
      token = scanner.parse_token

      if token&.start_with?('@')
        case token
        when '@entry'
          @current_doc.enum_entry_briefs << scanner.parse_paragraph.strip
        when '@end'
          break
        end
      elsif token&.include?('CF_ENUM(')
        # Extract enum entry name
        entry = token.gsub('CF_ENUM(', '').split(',').first
        @current_doc.enum_entries << entry if entry
      end
    end

    flush_doc
  end

  def parse_function(scanner)
    @current_doc = Doc.new
    @current_doc.type = :function
    @current_doc.file = @current_file

    parse_comment_block(scanner)

    # Parse function signature
    signature = scanner.parse_line.strip
    signature = signature.gsub('CF_API ', '')
                        .gsub('CF_CALL ', '')
                        .gsub('CF_INLINE ', '')

    # Remove trailing brace if present
    if idx = signature.index(' {')
      signature = signature[0...idx]
    end

    @current_doc.signature = signature
    flush_doc
  end

  def parse_struct(scanner)
    @current_doc = Doc.new
    @current_doc.type = :struct
    @current_doc.file = @current_file

    parse_comment_block(scanner)
    doc_index = @docs.length
    flush_doc

    # Parse struct members and functions
    while !scanner.done?
      token = scanner.parse_token

      if token&.start_with?('@')
        case token
        when '@member'
          brief = scanner.parse_paragraph.strip
          scanner.parse_token # Skip */
          member = scanner.parse_line.strip
                          .gsub('CF_INLINE ', '')
                          .gsub(';', '')
          @docs[doc_index].member_briefs << brief
          @docs[doc_index].members << member
        when '@function'
          @docs[doc_index].member_functions << @docs.length
          parse_function(scanner)
          @docs.last.this_index = doc_index
        when '@end'
          break
        end
      end
    end
  end

  def parse_comment_block(scanner)
    @current_doc.title = scanner.parse_paragraph.strip

    while !scanner.done?
      token = scanner.parse_token
      break if token == '*/'

      if token&.start_with?('@')
        parse_command(scanner, token)
      end
    end
  end

  def parse_command(scanner, command)
    case command
    when '@brief'
      @current_doc.brief = scanner.parse_paragraph.strip
    when '@example'
      @current_doc.example_brief = scanner.parse_single_comment_line.strip
      @current_doc.example = scanner.parse_paragraph(true)
    when '@remarks'
      @current_doc.remarks = scanner.parse_paragraph.strip
    when '@related'
      @current_doc.related = scanner.parse_paragraph.strip.split(/\s+/)
    when '@param'
      param_name = scanner.parse_token
      @current_doc.param_names << param_name
      @current_doc.param_briefs << scanner.parse_paragraph.strip
    when '@return'
      @current_doc.return_value = scanner.parse_paragraph.strip
    when '@category'
      @current_doc.web_category = scanner.parse_paragraph.strip
      @categories[@current_doc.web_category] = true
    end
  end

  def flush_doc
    return if @current_doc.title.empty?

    # Generate file path
    path = @docs_dir.join(@current_doc.web_category)
    filename = @current_doc.title.downcase.gsub(' ', '_') + '.md'
    @current_doc.path = path.join(filename)

    # Check for duplicates
    if @page_to_doc_index.has_key?(filename)
      other_doc = @docs[@page_to_doc_index[filename]]
      raise "Duplicate page for #{filename} (found in #{@current_doc.file}, previously in #{other_doc.file})"
    end

    @page_to_doc_index[filename] = @docs.length
    @category_index_lists[@current_doc.web_category] << @current_doc.title
    @docs << @current_doc
    @current_doc = Doc.new
  end

  def auto_generate_all_links
    @docs.each do |doc|
      doc.brief = auto_generate_links(doc.brief)
      doc.param_briefs = doc.param_briefs.map { |b| auto_generate_links(b) }
      doc.enum_entry_briefs = doc.enum_entry_briefs.map { |b| auto_generate_links(b) }
      doc.member_briefs = doc.member_briefs.map { |b| auto_generate_links(b) }
      doc.return_value = auto_generate_links(doc.return_value)
      doc.example_brief = auto_generate_links(doc.example_brief)
      doc.example = auto_generate_links(doc.example)
      doc.remarks = auto_generate_links(doc.remarks)

      # Process related links
      doc.related = doc.related.reject { |r| r == doc.title }.map do |related|
        linkify(related, related, false) + "  "
      end
    end
  end

  def auto_generate_links(text)
    return text if text.nil? || text.empty?

    result = text.dup

    # Find all text in backticks
    text.scan(/`([^`]+)`/).each do |match|
      scan_text = match[0]
      if doc_has_link?(scan_text)
        link = doc_get_link(scan_text)
        replacement = "[#{scan_text}](..#{link})"
        result = result.gsub("`#{scan_text}`", replacement)
      end
    end

    result
  end

  def linkify(text, scan, use_ticks = true)
    if doc_has_link?(scan)
      link = doc_get_link(scan)
      coded_link = "[#{scan}](..#{link})"
      scan_formatted = use_ticks ? "`#{scan}`" : scan
      text.gsub(scan_formatted, coded_link)
    else
      text
    end
  end

  def doc_has_link?(title)
    filename = title.downcase.gsub(' ', '_') + '.md'
    @page_to_doc_index.has_key?(filename)
  end

  def doc_get_link(title)
    filename = title.downcase.gsub(' ', '_') + '.md'
    index = @page_to_doc_index[filename]
    return '' unless index

    doc = @docs[index]
    relative_path = doc.path.relative_path_from(@docs_dir).to_s
    '/' + relative_path
  end

  def save_all_docs
    @docs.each do |doc|
      # Create directory if needed
      FileUtils.mkdir_p(doc.path.dirname)

      # Write doc file
      File.open(doc.path, 'w') do |fp|
        case doc.type
        when :enum
          doc.emit_title(fp)
          doc.emit_brief(fp)
          doc.emit_enum_entries(fp)
          doc.emit_example(fp)
          doc.emit_remarks(fp)
          doc.emit_related(fp)
        when :function
          doc.emit_title(fp)
          doc.emit_brief(fp)
          doc.emit_signature(fp)
          doc.emit_params(fp)
          doc.emit_return(fp)
          doc.emit_example(fp)
          doc.emit_remarks(fp)
          doc.emit_related(fp)
        when :struct
          doc.emit_title(fp)
          doc.emit_brief(fp)
          doc.emit_members(fp)
          doc.emit_member_function_links(fp, @docs)
          doc.emit_example(fp)
          doc.emit_remarks(fp)
          doc.emit_related(fp)
        end
      end

      puts "Wrote #{doc.path}"
    end
  end

  def generate_api_reference
    path = @docs_dir.join('api_reference.md')

    File.open(path, 'w') do |fp|
      fp.puts "[//]: # (This file is automatically generated by Cute Framework's docs parser.)"
      fp.puts "[//]: # (Do not edit this file by hand!)"
      fp.puts "[//]: # (See: https://github.com/RandyGaul/cute_framework/blob/master/scripts/docs_parser.rb)"
      fp.puts "# API Reference\n\n"
      fp.puts "This is a list of all functions in Cute Framework organized by categories. "
      fp.puts "This is great for users that want to see all the available functionality laid out plainly.\n\n\n"

      # Sort categories alphabetically
      sorted_categories = @categories.keys.sort { |a, b| a.downcase <=> b.downcase }

      sorted_categories.each do |category|
        fp.puts "## #{category}\n\n"

        # Get all items for this category
        items = @category_index_lists[category]

        # Separate by type
        functions = []
        structs = []
        enums = []

        items.each do |title|
          filename = title.downcase.gsub(' ', '_') + '.md'
          index = @page_to_doc_index[filename]
          doc = @docs[index]

          case doc.type
          when :function
            functions << title
          when :struct
            structs << title
          when :enum
            enums << title
          end
        end

        # Output functions
        if functions.any?
          save_api_reference_links(fp, category, functions.sort { |a, b| a.downcase <=> b.downcase }, 'functions')
        end

        # Output structs
        if structs.any?
          save_api_reference_links(fp, category, structs.sort { |a, b| a.downcase <=> b.downcase }, 'structs')
        end

        # Output enums
        if enums.any?
          save_api_reference_links(fp, category, enums.sort { |a, b| a.downcase <=> b.downcase }, 'enums')
        end
      end
    end

    puts "Wrote #{path}"
  end

  def save_api_reference_links(fp, category, pages, type)
    return if pages.empty?

    fp.puts "### #{type}"
    pages.each do |page|
      page_lower = page.downcase.gsub(' ', '_')
      fp.puts "- [#{page}](#{category}/#{page_lower}.md)"
    end
    fp.puts "\n\n"

    # Add related links if any
    related = CATEGORY_RELATED_LINKS[category]
    if related && related.any?
      fp.puts "### Related Reading"
      related.each do |link|
        fp.puts link
      end
      fp.puts
    end
  end

  def cleanup_old_docs
    @categories.keys.each do |category|
      dir_path = @docs_dir.join(category)
      next unless Dir.exist?(dir_path)

      Dir.glob(dir_path.join('*.md')).each do |file|
        filename = File.basename(file)
        next if ['enums.md', 'functions.md', 'structs.md'].include?(filename)

        unless @page_to_doc_index.has_key?(filename)
          File.delete(file)
          puts "Removed old file: #{file}"
        end
      end
    end
  end

  # Scanner class for parsing documentation
  class Scanner
    def initialize(content, filename)
      @content = content
      @filename = filename
      @pos = 0
      @lines = content.lines
      @current_line = 0
      @current_col = 0
    end

    def done?
      @pos >= @content.length
    end

    def parse_token
      token = ''

      # Skip whitespace
      while !done? && whitespace?(@content[@pos])
        advance
      end

      return nil if done?

      # Collect token
      while !done? && !whitespace?(@content[@pos])
        token += @content[@pos]
        advance
      end

      token.empty? ? nil : token
    end

    def parse_paragraph(example = false)
      paragraph = ''

      while !done?
        ch = @content[@pos]

        if ch == '\n'
          paragraph += ch
          advance

          # Check for end of comment
          if peek_string(' */') || peek_string('*/')
            break
          elsif peek_string(' * ')
            advance(3)
          elsif peek_string(' *')
            advance(2)
          end
        elsif ch == '@' && !example
          break
        elsif peek_string('*/')
          break
        else
          paragraph += ch unless ch == '\r'
          advance
        end
      end

      unless example
        paragraph = paragraph.strip.gsub(/\n\s+/, "\n")
      else
        paragraph = paragraph.gsub(/\n    /, "\n")
      end

      paragraph
    end

    def parse_single_comment_line
      line = ''

      # Skip initial whitespace and asterisk
      if peek_string(' * ')
        advance(3)
      elsif peek_string(' *')
        advance(2)
      end

      # Read until newline
      while !done? && @content[@pos] != "\n"
        line += @content[@pos]
        advance
      end

      line.strip
    end

    def parse_line
      line = ''

      # Skip newline if present
      advance if @content[@pos] == "\n"

      # Read until newline
      while !done? && @content[@pos] != "\n"
        line += @content[@pos]
        advance
      end

      line.strip
    end

    private

    def advance(count = 1)
      count.times do
        if @content[@pos] == "\n"
          @current_line += 1
          @current_col = 0
        else
          @current_col += 1
        end
        @pos += 1
      end
    end

    def peek_string(str)
      return false if @pos + str.length > @content.length
      @content[@pos, str.length] == str
    end

    def whitespace?(ch)
      ch =~ /\s/
    end
  end
end

# Main execution
if __FILE__ == $0
  # Determine paths relative to script location
  script_dir = File.dirname(File.expand_path(__FILE__))
  project_root = File.dirname(script_dir)

  include_dir = File.join(project_root, 'include')
  docs_dir = File.join(project_root, 'docs')

  unless Dir.exist?(include_dir)
    puts "Error: Include directory not found at #{include_dir}"
    exit 1
  end

  unless Dir.exist?(docs_dir)
    puts "Error: Docs directory not found at #{docs_dir}"
    exit 1
  end

  puts "Parsing headers from: #{include_dir}"
  puts "Writing docs to: #{docs_dir}"

  parser = DocsParser.new(include_dir, docs_dir)
  parser.parse_all
end